name: Test with Godot
description: Run gdzig tests with a specific Godot version

inputs:
  godot-version:
    description: Godot version to test with
    required: true
  cache-key:
    description: Cache key for Zig build artifacts
    required: true

runs:
  using: composite
  steps:
    - name: Setup Zig
      uses: mlugg/setup-zig@v2
      with:
        cache-key: ${{ inputs.cache-key }}

    - name: Run tests
      shell: bash
      run: zig build test -Dgodot=${{ inputs.godot-version }} -Dfetch-godot=true
